apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auditor-cluster-role

rules:

- apiGroups: [""]
  resources:
    - nodes
    - namespaces
    - persistentvolumes
  verbs:
    - get
    - list
    - watch
