apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa
  namespace: card-processing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: card-processing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auditor-sa
  namespace: card-processing
