persistence:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: NodePort
  nodePort: 30300

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 12

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 120
  timeoutSeconds: 5
  periodSeconds: 20
  failureThreshold: 6

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
