alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false

  retention: "3h"

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
