replicaCount: 2

image:
  repository: rvsivakrishna/payment-api
  tag: "v9"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

config:
  APP_ENV: development
  CARD_PROCESSOR_URL: http://card-processor-service:8080/process
  LOG_LEVEL: INFO

secret:
  existingSecret: card-processing-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: true
  className: nginx
  name: payment-ingress
  host: payment.bank.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20

networkPolicy:
  enabled: true
  ingressNamespace:
    name: ingress-nginx
  port: 8080

rollingUpdate:
  maxSurge: "25%"
  maxUnavailable: "25%"

probes:
  startup:
    path: /
    port: 8080
    periodSeconds: 5
    failureThreshold: 30

  liveness:
    path: /
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

  readiness:
    path: /
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

config:
  APP_ENV: development
  CARD_PROCESSOR_URL: http://card-processor-service:8080/process
  LOG_LEVEL: INFO

cardProcessor:
  enabled: true
  replicaCount: 2
  image:
    repository: rvsivakrishna/card-processor
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    port: 8080
    targetPort: 8080

fraudService:
  enabled: true
  replicaCount: 1
  image:
    repository: rvsivakrishna/fraud-service
    tag: "v2"
    pullPolicy: IfNotPresent
  service:
    port: 8081
    targetPort: 8081

mysql:
  enabled: true

  replicaCount: 1

  image:
    repository: mysql
    tag: "8.4"
    pullPolicy: IfNotPresent

  secretName: mysql-secret

  service:
    port: 3306

  persistence:
    size: 2Gi
    storageClassName: local-path

auditService:
  enabled: true
  replicaCount: 1

  image:
    repository: rvsivakrishna/audit-service
    digest: "sha256:bcc71bb106b65be2dd99d47c46d30acccc74d34adac6194d1371e32dfaf37d05"
    pullPolicy: IfNotPresent

  service:
    port: 8082
    targetPort: 8082

  mysqlSecret: mysql-secret

  persistence:
    enabled: true
    existingClaim: ""
    size: 1Gi
    storageClassName: local-path

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

dbInit:
  enabled: true
  image: mysql:8.4
  host: mysql-service
  port: 3306
  secretName: mysql-secret
  configMapName: mysql-init-script

networkPolicies:
  enabled: true

  defaultDeny:
    enabled: true

  paymentToCardProcessor:
    enabled: true
    port: 8080

  paymentToFraud:
    enabled: true
    port: 8081

  paymentToAudit:
    enabled: true
    port: 8082

  database:
    enabled: true
    port: 3306
