apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: card-processing

type: Opaque

stringData:

  MYSQL_ROOT_PASSWORD: root123

  MYSQL_DATABASE: auditdb

  MYSQL_USER: audituser

  MYSQL_PASSWORD: audit123
