apiVersion: v1
kind: ConfigMap
metadata:
  name: card-processing-config
  namespace: card-processing

data:
  LOG_LEVEL: "INFO"
  APP_ENV: "development"
  CARD_PROCESSOR_URL: "http://card-processor-service:8080/process"
