apiVersion: v1
kind: Service

metadata:
  name: fraud-service
  namespace: card-processing

spec:

  selector:
    app: fraud-service

  ports:

  - port: 8081
    targetPort: 8081

  type: ClusterIP
