apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
  namespace: card-processing
  labels:
    app: fraud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
    spec:
      containers:
      - name: fraud-service
        image: rvsivakrishna/fraud-service:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: card-processing-config
        - secretRef:
            name: card-processing-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
