apiVersion: v1
kind: Service

metadata:
  name: payment-api-service
  namespace: card-processing

spec:

  selector:
    app: payment-api

  ports:

  - port: 8080
    targetPort: 8080

  type: ClusterIP
