apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-api
  namespace: card-processing
  labels:
    app: payment-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payment-api

  template:

    metadata:
      labels:
        app: payment-api

    spec:
      containers:

      - name: payment-api

        image: rvsivakrishna/payment-api:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: card-processing-config

        - secretRef:
            name: card-processing-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "250m"
            memory: "256Mi"
