apiVersion: v1
kind: Secret
metadata:
  name: card-processing-secret
  namespace: card-processing

type: Opaque

stringData:
  API_KEY: "bank123456"
  DB_USERNAME: "bankuser"
  DB_PASSWORD: "SecurePass@123"
