apiVersion: apps/v1
kind: Deployment

metadata:
  name: audit-service
  namespace: card-processing

spec:
  replicas: 1

  selector:
    matchLabels:
      app: audit-service

  template:
    metadata:
      labels:
        app: audit-service

    spec:
      containers:
        - name: audit-service

          image: rvsivakrishna/audit-service@sha256:bcc71bb106b65be2dd99d47c46d30acccc74d34adac6194d1371e32dfaf37d05
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8082

          env:
            - name: MYSQL_HOST
              value: "mysql-service"

            - name: MYSQL_PORT
              value: "3306"

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          volumeMounts:
            - name: audit-storage
              mountPath: /data

      volumes:
        - name: audit-storage
          persistentVolumeClaim:
            claimName: card-transactions-pvc
