apiVersion: v1
kind: PersistentVolume
metadata:
  name: card-transactions-pv
spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/card-transactions
