apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: card-transactions-pvc
  namespace: card-processing

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
