{{- if and .Values.auditService.enabled .Values.auditService.persistence.enabled (not .Values.auditService.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: card-transactions-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: {{ .Values.auditService.persistence.storageClassName }}

  resources:
    requests:
      storage: {{ .Values.auditService.persistence.size }}
{{- end }}
