apiVersion: v1
kind: ConfigMap

metadata:
  name: card-processing-config
  labels:
    {{- include "payment-api.labels" . | nindent 4 }}

data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  CARD_PROCESSOR_URL: {{ .Values.config.CARD_PROCESSOR_URL | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
