{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-ingress-to-payment-api
  labels:
    {{- include "payment-api.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: payment-api
      app.kubernetes.io/instance: payment-api

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace.name }}

      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.port }}
{{- end }}
