apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  labels:
    {{- include "payment-api.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP